config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  get '/help' => 'pages#help', as: 'help'

  root 'dashboard#index'

  get '/login' => 'sessions#new', as: 'login'
  post '/one_time_token' => 'sessions#one_time_token', as: 'one_time_token'
  post '/login' => 'sessions#create'

  get '/logout' => 'sessions#destroy', as: 'logout'

  resources :matches, only: [:index, :show]
  resources :questions, only: [:index, :show]
  resources :bets, only: [:index, :show]

  get '/my_bet' => 'my_bet#show', as: 'my_bet'
  get '/my_bet/matches' => 'my_bet#matches', as: 'my_bet_matches'
  get '/my_bet/questions' => 'my_bet#questions', as: 'my_bet_questions'

  get '/my_bet/payment' => 'payments#new', as: 'my_bet_payment'
  post '/my_bet/payment' => 'payments#create'
  post '/payment_notifications' => 'payments#update', as: 'payment_notifications'

  get  '/my_bet/matches/:match_id' => 'match_bets#edit', as: 'my_match_bet'
  post '/my_bet/matches/:match_id' => 'match_bets#create'
  put  '/my_bet/matches/:match_id' => 'match_bets#update'

  get  '/my_bet/questions/:question_id' => 'question_bets#edit', as: 'my_question_bet'
  post '/my_bet/questions/:question_id' => 'question_bets#create'
  put  '/my_bet/questions/:question_id' => 'question_bets#update'

  namespace :admin do
    resources :matches, only: [:edit, :update]
    resources :questions, only: [:edit, :update]
  end

  # TODO limit access to admins, see https://github.com/mperham/sidekiq/wiki/Monitoring#security
  mount Sidekiq::Web => '/admin/sidekiq'

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  skip_before_action :require_login, only: [:index]

  # GET /
  # Via: root_path
  def index
  end

end

app/views/dashboard/index.html.erb
<% content_for(:title) { t('.title', app_name: ENV['APP_NAME']) } %>

<% if logged_in? %>
  <div class="row">
    <div class="small-12 column">
      <h2><%= t '.welcome_back' %></h2>
      <p><%= t('.how_is_your_bet', link: link_to(t('.your_bet'), my_bet_path)).html_safe %>.</p>
    </div>
  </div>
<% else %>
  <div class="row">
    <div class="small-12 column">
      <h2><%= t '.welcome' %></h2>
      <p><%= t('.read_the_rules_and_sign_up', rules_link: link_to(t('.the_rules'), help_path), login_link: link_to(t('.do_login'), login_path)).html_safe %>.</p>
    </div>
  </div>
<% end %>