config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  get '/help' => 'pages#help', as: 'help'

  root 'dashboard#index'

  get '/login' => 'sessions#new', as: 'login'
  post '/one_time_token' => 'sessions#one_time_token', as: 'one_time_token'
  post '/login' => 'sessions#create'

  get '/logout' => 'sessions#destroy', as: 'logout'

  resources :matches, only: [:index, :show]
  resources :questions, only: [:index, :show]
  resources :bets, only: [:index, :show]

  get '/my_bet' => 'my_bet#show', as: 'my_bet'
  get '/my_bet/matches' => 'my_bet#matches', as: 'my_bet_matches'
  get '/my_bet/questions' => 'my_bet#questions', as: 'my_bet_questions'

  get '/my_bet/payment' => 'payments#new', as: 'my_bet_payment'
  post '/my_bet/payment' => 'payments#create'
  post '/payment_notifications' => 'payments#update', as: 'payment_notifications'

  get  '/my_bet/matches/:match_id' => 'match_bets#edit', as: 'my_match_bet'
  post '/my_bet/matches/:match_id' => 'match_bets#create'
  put  '/my_bet/matches/:match_id' => 'match_bets#update'

  get  '/my_bet/questions/:question_id' => 'question_bets#edit', as: 'my_question_bet'
  post '/my_bet/questions/:question_id' => 'question_bets#create'
  put  '/my_bet/questions/:question_id' => 'question_bets#update'

  namespace :admin do
    resources :matches, only: [:edit, :update]
    resources :questions, only: [:edit, :update]
  end

  # TODO limit access to admins, see https://github.com/mperham/sidekiq/wiki/Monitoring#security
  mount Sidekiq::Web => '/admin/sidekiq'

end

app/controllers/my_bet_controller.rb
class MyBetController < ApplicationController

  before_action :find_bet

  # GET /my_bet
  # Via: my_bet_path
  #
  # Shows a summary of the current user's bet
  def show
    @_matches = @_bet.bettable_matches_still_to_bet.all
    @_questions = @_bet.bettable_questions_still_to_bet.all

    @matches = MatchPresenter.map(@_matches)
    @questions = QuestionPresenter.map(@_questions)
  end

  # GET /my_bet/matches?filter=[betted|to_bet]
  # Via: my_bet_matches_path(filter: [:betted|:to_bet])
  #
  # List all the matches of the current bet.
  def matches
    @_matches = @_bet.filtered_matches(filtered_params[:filter]).all
    @matches = MatchPresenter.map(@_matches)

    @_match_bets = @_bet.filtered_match_bets(filtered_params[:filter]).all
    @match_bets = MatchBetPresenter.map(@_match_bets)
  end

  # GET /my_bet/questions?filter=[betted|to_bet]
  # Via: my_bet_questions_path(filter: [:betted|:to_bet])
  #
  # List all the questions of the current bet.
  def questions
    @_questions = @_bet.filtered_questions(filtered_params[:filter]).all
    @questions = QuestionPresenter.map(@_questions)

    @_question_bets = @_bet.filtered_question_bets(filtered_params[:filter]).all
    @question_bets = QuestionBetPresenter.map(@_question_bets)
  end

  private

  def find_bet
    @_bet = current_user.bet
    @bet = BetPresenter.new(@_bet)
  end

  def filtered_params
    params.permit(:filter)
  end

end

app/views/my_bet/_bet.html.erb
<% index ||= 0 %>
<% index+= 1 %>
<tr>
  <td><%= index %></td>
  <td><%= bet.user.email %></td>
  <td><%= bet.score %></td>
</tr>

app/views/my_bet/_match_bet_list_info.html.erb
<tr>
  <td class="text-right hide-for-small-only" colspan="1">&nbsp;</td>
  <td class="text-left hide-for-small-only">
    <% if match.bettable? %>
      <span class="has-tip" title="<%= t '.you_may_change_your_bet_until', datetime: l(match.bettable_until, format: :detailed ) %>">
        <%= l match.bettable_until, format: '%H:%M' %>
      </span>
    <% else %>
      &nbsp;
    <% end %>
  </td>
  <td class="text-right hide-for-small-only" colspan="2"><%= t('.your_answer') %>:</td>
  <td class="text-center">
    <% if match_bet %>
      <%= match_bet.goals_a %> x <%= match_bet.goals_b %>
      <% if match_bet.penalty_winner %>
        <br /><%= match_bet.penalty_winner.name %>
        <br /><em>(<%= t('.on_penaltys') %>)</em>
      <% end %>
    <% else %>
      <em><%= t('.not_answered') %></em>
    <% end %>
  </td>
  <td class="text-center">
    <% if match_bet %>
      <%= match_bet.points_with_explanation %> <%= t('.points') %>
    <% else %>
      -
    <% end %>
  </td>
  <td class="text-center">
    <% if match.bettable? %>
      <% if match_bet %>
        <strong><%= link_to t('.update'), my_match_bet_path(match) %></strong>
      <% else %>
        <strong><%= link_to t('.create'), my_match_bet_path(match) %></strong>
      <% end %>
    <% else %>
      &nbsp;
    <% end %>
  </td>
</tr>

app/views/my_bet/_match_list_info.html.erb
<tr>
  <td><%= link_to "##{match.number}", match_path(match) %></td>
  <td class="text-left hide-for-small-only">
    <%= l match.played_at, format: '%H:%M' %>
  </td>
  <td class="text-center hide-for-small-only"><%= match.team_a_flag_or_? %></td>
  <td class="text-right"><%= match.team_a_name_or_? %></td>
  <td class="text-center">
    <%= match.goals_a_or_? %> x <%= match.goals_b_or_? %>
    <% if match.with_known_penalty_goals? %>
      <br /><%= match.penalty_goals_a_or_? %> x <%= match.penalty_goals_a_or_? %>
      <br /><em>(<%= t('.on_penaltys') %>)</em>
    <% end %>
  </td>
  <td class="text-left"><%= match.team_b_name_or_? %></td>
  <td class="text-center hide-for-small-only"><%= match.team_b_flag_or_? %></td>
</tr>

app/views/my_bet/_payment.html.erb
<% if bet.paid? %>
  <p><%= t '.bet_is_paid' %></p>
<% else %>
  <% if bet.paying? %>
    <p class="panel radius">
      <%= t '.bet_is_paying' %>
      <%= link_to t('.check_payment'), my_bet_payment_path %>.
    </p>
  <% else %>
    <p class="panel callout radius">
      <%= t '.bet_is_not_paid', date: l(bet.payment_deadline, format: :detailed) %>
      <%= link_to t('.pay_now'), my_bet_payment_path %>.
    </p>
  <% end %>
<% end %>

app/views/my_bet/_question_bet_list_info.html.erb
<tr>
  <td class="text-center">&nbsp;</td>

  <td class="text-left">
    <% if question.bettable? %>
      <span class="has-tip" title="<%= t '.you_may_change_your_bet_until', datetime: l(question.bettable_until, format: :detailed ) %>">
        <%= l question.bettable_until, format: :short %>
      </span>
    <% else %>
      &nbsp;
    <% end %>
  </td>

  <td class="text-right"><em><%= t('.your_answer') %></em></td>

  <td class="text-left">
    <% if question_bet %>
      <%= question_bet.answer_text %>
    <% else %>
      <span class="subheader"><%= t '.not_yet_answered' %></span>
    <% end %>
  </td>

  <td class="text-center">
    <% if question.bettable? %>
      <% if question_bet %>
        <strong><%= link_to t('.update'), my_question_bet_path(question) %></strong>
      <% else %>
        <strong><%= link_to t('.create'), my_question_bet_path(question) %></strong>
      <% end %>
    <% else %>
      &nbsp;
    <% end %>
  </td>

  <td class="text-center">
    <% if question_bet %>
      <%= question_bet.points_with_explanation %> <%= t('.points') %>
    <% else %>
      -
    <% end %>
  </td>
</tr>

app/views/my_bet/_question_list_info.html.erb
<tr>
  <td class="text-center"><%= link_to "##{question.number}", question_path(question) %></td>

  <td class="text-left" colspan="2"><%= question.body %></td>

  <td class="text-left" colspan="3">
    <% if question.answered? %>
      <%= question.answer_text %>
    <% else %>
      <span class="subheader"><%= t '.not_yet_answered' %></span>
    <% end %>
  </td>
</tr>

app/views/my_bet/matches.html.erb
<% content_for(:title) { t('.title') } %>

<div class="row">
  <div class="small-12 column">
    <h2><%= t '.my_bet' %></h2>
    <h3><%= Match.model_name.human(count: 2) %></h3>

    <dl class="sub-nav">
      <dt><%= t '.filter' %>:</dt>
      <dd class="<%= 'active' if (current_filter.blank? || current_filter.all?) %>"><%= link_to t('.all'), my_bet_matches_path %></dd>
      <dd class="<%= 'active' if current_filter.betted? %>"><%= link_to t('.betted'), my_bet_matches_path(filter: :betted) %></dd>
      <dd class="<%= 'active' if current_filter.to_bet? %>"><%= link_to t('.to_bet'), my_bet_matches_path(filter: :to_bet) %></dd>
    </dl>
  </div>
</div>

<div class="row">
  <div class="small-12 column">
    <% if @matches.empty? %>
      <p><%= t( current_filter.blank? ? '.none_to_show' : ".none_to_show_#{current_filter}") %>.</p>
    <% else %>
      <% @matches.group_by { |m| {date: m.played_at.to_date, round: m.round_text} }.each do |grouping, matches| %>
        <h5><%= l grouping[:date], format: :detailed %>, <%= grouping[:round] %></h5>
        <% matches.each do |match| %>
          <% match_bet = @match_bets.detect { |qb| qb.match_id == match.id } %>
          <table>
            <tbody>
              <%= render partial: 'my_bet/match_list_info', locals: { match: match } %>
              <%= render partial: 'my_bet/match_bet_list_info', locals: { match: match, match_bet: match_bet } %>
            </tbody>
          </table>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/my_bet/questions.html.erb
<% content_for(:title) { t('.title') } %>

<div class="row">
  <div class="small-12 column">
    <h2><%= t '.my_bet' %></h2>
    <h3><%= Question.model_name.human(count: 2) %></h3>

    <dl class="sub-nav">
      <dt><%= t '.filter' %>:</dt>
      <dd class="<%= 'active' if current_filter.blank? %>"><%= link_to t('.all'), my_bet_questions_path %></dd>
      <dd class="<%= 'active' if current_filter.betted? %>"><%= link_to t('.betted'), my_bet_questions_path(filter: :betted) %></dd>
      <dd class="<%= 'active' if current_filter.to_bet? %>"><%= link_to t('.to_bet'), my_bet_questions_path(filter: :to_bet) %></dd>
    </dl>
  </div>
</div>

<div class="row">
  <div class="small-12 column">
    <% if @questions.empty? %>
      <p><%= t( current_filter.blank? ? '.none_to_show' : ".none_to_show_#{current_filter}") %>.</p>
    <% else %>
      <% @questions.group_by { |q| q.answer_type }.each do |answer_type, questions| %>
        <h5><%= t("activerecord.attributes.question.answer_types.#{answer_type}") %></h5>
        <% questions.each do |question| %>
          <% question_bet = @question_bets.detect { |qb| qb.question_id == question.id } %>
          <table>
            <tbody>
              <%= render partial: 'my_bet/question_list_info', locals: { question: question } %>
              <%= render partial: 'my_bet/question_bet_list_info', locals: { question: question, question_bet: question_bet } %>
            </tbody>
          </table>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/my_bet/show.html.erb
<% content_for(:title) { t('.title') } %>

<div class="row">
  <div class="small-12 column">
    <h2><%= t '.title' %></h2>
    <p><%= t '.current_score' %>: <%= @bet.points %></p>
  </div>
</div>

<div class="row">
  <div class="small-12 column">
    <%= render partial: 'my_bet/payment', locals: {bet: @bet} %>
  </div>
</div>

<div class="row">
  <div class="small-6 column">
    <% if @matches.any? %>
      <p class="panel callout radius"><strong><%= t('.you_have_matches_to_bet', count: @matches.size, link: link_to(t('.do_it_now'), my_match_bet_path(@matches.first))).html_safe %>!</strong></p>
    <% end %>
  </div>
  <div class="small-6 column">
    <% if @questions.any? %>
      <p class="panel callout radius"><strong><%= t('.you_have_questions_to_bet', count: @questions.size, link: link_to(t('.do_it_now'), my_question_bet_path(@questions.first))).html_safe %>!</strong></p>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="small-6 column">
    <h3>
      <%= Match.model_name.human(count: 2) %>
      <small>(<%= link_to t('common.view'), my_bet_matches_path %>)</small>
    </h3>
    <p><%= t '.matches_betted', count: @bet.matches_count %> (<%= link_to t('common.view'), my_bet_matches_path(filter: :betted) %>)</p>
    <p><%= t '.matches_to_bet', count: @matches.size %> (<%= link_to t('common.view'), my_bet_matches_path(filter: :to_bet) %>)</p>
  </div>
  <div class="small-6 column">
    <h3>
      <%= Question.model_name.human(count: 2) %>
      <small>(<%= link_to t('common.view'), my_bet_questions_path %>)</small>
    </h3>
    <p><%= t '.questions_betted', count: @bet.questions_count %> (<%= link_to t('common.view'), my_bet_questions_path(filter: :betted) %>)</p>
    <p><%= t '.questions_to_bet', count: @questions.size %> (<%= link_to t('common.view'), my_bet_questions_path(filter: :to_bet) %>)</p>
  </div>
</div>