config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  get '/help' => 'pages#help', as: 'help'

  root 'dashboard#index'

  get '/login' => 'sessions#new', as: 'login'
  post '/one_time_token' => 'sessions#one_time_token', as: 'one_time_token'
  post '/login' => 'sessions#create'

  get '/logout' => 'sessions#destroy', as: 'logout'

  resources :matches, only: [:index, :show]
  resources :questions, only: [:index, :show]
  resources :bets, only: [:index, :show]

  get '/my_bet' => 'my_bet#show', as: 'my_bet'
  get '/my_bet/matches' => 'my_bet#matches', as: 'my_bet_matches'
  get '/my_bet/questions' => 'my_bet#questions', as: 'my_bet_questions'

  get '/my_bet/payment' => 'payments#new', as: 'my_bet_payment'
  post '/my_bet/payment' => 'payments#create'
  post '/payment_notifications' => 'payments#update', as: 'payment_notifications'

  get  '/my_bet/matches/:match_id' => 'match_bets#edit', as: 'my_match_bet'
  post '/my_bet/matches/:match_id' => 'match_bets#create'
  put  '/my_bet/matches/:match_id' => 'match_bets#update'

  get  '/my_bet/questions/:question_id' => 'question_bets#edit', as: 'my_question_bet'
  post '/my_bet/questions/:question_id' => 'question_bets#create'
  put  '/my_bet/questions/:question_id' => 'question_bets#update'

  namespace :admin do
    resources :matches, only: [:edit, :update]
    resources :questions, only: [:edit, :update]
  end

  # TODO limit access to admins, see https://github.com/mperham/sidekiq/wiki/Monitoring#security
  mount Sidekiq::Web => '/admin/sidekiq'

end

app/models/bet.rb
class Bet < ActiveRecord::Base

  belongs_to :user
  has_one :payment, dependent: :destroy
  has_many :match_bets, dependent: :destroy
  has_many :question_bets, dependent: :destroy
  has_many :matches, through: :match_bets
  has_many :questions, through: :question_bets

  validates :user,
    presence: true

  validates :points,
    presence: true,
    numericality: { only_integer: true, greater_than_or_equal_to: 0, allow_blank: true }

  def score
    match_bets.sum(:points) + question_bets.sum(:points)
  end

  # TODO spec
  def score!
    self.update_attributes!(points: self.score)
  end

  def cost
    BigDecimal(ENV.fetch('APP_BET_COST', 25))
  end

  def to_prize
    BigDecimal(ENV.fetch('APP_BET_PRIZE', 20))
  end

  def payment_deadline
    Time.zone.parse('2014-06-12 17:00:00 -0300')
  end

  def prize_split
    {
      first: Float(ENV.fetch('APP_PRIZE_FIRST', 65.0)),
      second: Float(ENV.fetch('APP_PRIZE_SECOND', 25.0)),
      third: Float(ENV.fetch('APP_PRIZE_THIRD', 10.0)),
    }
  end

  # TODO spec
  def paid?
    self.payment.present? && self.payment.paid?
  end

  # TODO spec
  def paying?
    self.payment.present? && self.payment.paying?
  end

  # TODO spec
  def match_bets_percentage
    bettable_count = Match.with_known_teams.count
    return 0.0 if bettable_count == 0
    (self.match_bets.count / bettable_count.to_f) * 100.0
  end
  # TODO spec
  def question_bets_percentage
    bettable_count = Question.count
    return 0.0 if bettable_count == 0
    (self.question_bets.count / bettable_count.to_f) * 100.0
  end
  # TODO spec
  def percentage
    bettable_count = (Match.with_known_teams.count + Question.count)
    return 0.0 if bettable_count == 0
    ((self.match_bets.count + self.question_bets.count) / bettable_count.to_f) * 100.0
  end

  def matches_still_to_bet
    self.matches.where.not(id: self.matches.pluck(:id))
  end

  def bettable_matches
    Match.bettable.ordered
  end

  def bettable_matches_still_to_bet
    self.bettable_matches.where.not(id: self.matches.pluck(:id))
  end

  def bettable_matches_already_betted
    self.matches.bettable.ordered
  end

  def bettable_questions
    Question.bettable.ordered
  end

  def bettable_questions_still_to_bet
    Question.bettable.ordered.where.not(id: self.questions.pluck(:id))
  end

  def bettable_questions_already_betted
    self.questions.bettable.ordered
  end

  # TODO spec
  def filtered_matches(filter=nil)
    case filter.to_s
    when 'betted'
      self.matches.ordered
    when 'to_bet'
      self.bettable_matches_still_to_bet
    else
      Match.with_known_teams.ordered
    end
  end

  # TODO spec
  def filtered_questions(filter=nil)
    case filter.to_s
    when 'betted'
      self.questions.ordered
    when 'to_bet'
      self.bettable_questions_still_to_bet
    else
      Question.unscoped.ordered
    end
  end

  # TODO spec
  def filtered_question_bets(filter=nil)
    case filter.to_s
    when 'to_bet'
      self.question_bets.where('1=2')
    else
      self.question_bets.scope
    end
  end

  # TODO spec
  def filtered_match_bets(filter=nil)
    case filter.to_s
    when 'to_bet'
      self.match_bets.where('1=2')
    else
      self.match_bets.scope
    end
  end

end

app/controllers/bets_controller.rb
class BetsController < ApplicationController

  # GET /bets
  # Via: bets_path
  def index
    @_bets = Bet.includes(:payment).order("points desc").all
    @bets = BetPresenter.map(@_bets)
    @paid_bets_count = @bets.select(&:paid?).size
    @paying_bets_count = @bets.select(&:paying?).size
  end

  # GET /bets/:id
  # Via: bet_path(:id)
  #
  # Shows a summary of the requested bet
  # TODO spec
  def show
    @_bet = Bet.find(params[:id])
    @bet = BetPresenter.new(@_bet)
  end

end

app/views/bets/_bet.html.erb
<% index ||= 0 %>
<% index+= 1 %>
<tr>
  <td><%= index %></td>
  <td><%= bet.user.email %></td>
  <td><%= bet.points %></td>
</tr>

app/views/bets/_match.html.erb
<div class="row">
  <div id="<%= match.css_id %>" class="small-10 small-centered column match">
    <h4><%= Match.model_name.human(count: 1) %> #<%= match.number %></h4>
    <p>
      <%= match.round_text %>
      <% if match.group.present? %>
        | <%= Match.human_attribute_name(:group) %> <%= match.group %>
      <% end %>
    </p>
    <p><%= l match.played_at, format: :detailed %> @ <%= match.played_on_text %></p>

    <% if match.played? %>
      <p><%= t '.result' %>:</p>
      <p>
        <%= match.team_a_flag %>
        <%= match.team_a_name %>
        <%= match.goals_a %>
         X
        <%= match.goals_b %>
        <%= match.team_b_name %>
        <%= match.team_b_flag %>
      </p>
    <% else %>
      <p><%= t '.result' %>: <span class="subheader"><%= t '.not_yet_played' %></span></p>
      <p>
        <%= match.team_a_flag %>
        <%= match.team_a_name %>
        ?
         X
        ?
        <%= match.team_b_name %>
        <%= match.team_b_flag %>
      </p>
    <% end %>

    <% if match.betted_by?(@_bet) %>
      <% match_bet = @match_bets.detect { |qb| qb.match_id == match.id } %>
      <p><%= t '.your_answer' %>:</p>
      <p>
        <%= match.team_a_flag %>
        <%= match.team_a_name %>
        <%= match_bet.goals_a %>
         X
        <%= match_bet.goals_b %>
        <%= match.team_b_name %>
        <%= match.team_b_flag %>
        <span>(<%= link_to t('.update'), match_bet_path(match) %>)</span>
      </p>
      <p><%= t '.you_may_change_your_bet_until', datetime: l(match.bettable_until, format: :detailed ) %></p>
    <% else %>
      <p>
        <%= t '.your_answer' %>: <span class="subheader"><%= t '.not_answered' %></span>
        <span>(<%= link_to t('.create'), match_bet_path(match) %>)</span>
      </p>
      <p><%= t '.you_may_make_your_bet_until', datetime: l(match.bettable_until, format: :detailed ) %></p>
    <% end %>
  </div>
</div>

app/views/bets/_payment.html.erb
<% if bet.paid? %>
  <p><%= t '.bet_is_paid' %></p>
<% else %>
  <% if bet.paying? %>
    <p class="panel radius">
      <%= t '.bet_is_paying' %>
      <%= link_to t('.check_payment'), bet_payment_path %>.
    </p>
  <% else %>
    <p class="panel callout radius">
      <%= t '.bet_is_not_paid', date: l(bet.payment_deadline, format: :detailed) %>
      <%= link_to t('.pay_now'), bet_payment_path %>.
    </p>
  <% end %>
<% end %>

app/views/bets/_question.html.erb
<div class="row">
  <div id="<%= question.css_id %>" class="small-10 small-centered column question">
    <h4><%= Question.model_name.human(count: 1) %> #<%= question.number %></h4>
    <p><strong><%= question.body %></strong></p>

    <% if question.answered? %>
      <p><%= Question.human_attribute_name(:answer) %>: <%= question.answer %></p>
    <% else %>
      <p><%= Question.human_attribute_name(:answer) %>: <span class="subheader"><%= t '.not_yet_answered' %></span></p>
    <% end %>

    <% if question.betted_by?(@_bet) %>
      <% question_bet = @question_bets.detect { |qb| qb.question_id == question.id } %>
      <p>
        <%= t '.your_answer' %>: <%= question_bet.answer_text %>
        <span>(<%= link_to t('.update'), question_bet_path(question) %>)</span>
      </p>
      <p><%= t '.you_may_change_your_bet_until', datetime: l(question.bettable_until, format: :detailed ) %></p>
    <% else %>
      <p>
        <%= t '.your_answer' %>: <span class="subheader"><%= t '.not_answered' %></span>
        <span>(<%= link_to t('.create'), question_bet_path(question) %>)</span>
      </p>
      <p><%= t '.you_may_make_your_bet_until', datetime: l(question.bettable_until, format: :detailed ) %></p>
    <% end %>
  </div>
</div>

app/views/bets/index.html.erb
<% content_for(:title) { t('.title') } %>

<div class="row">
  <div class="small-12 column">
    <h2><%= Bet.model_name.human(count: 2) %></h2>
  </div>
</div>

<div class="row">
  <div class="small-9 column">
    <h3><%= t('.general_classification') %></h3>
    <table>
      <thead>
        <tr>
          <th class="hide-for-small-only"><%= t('.ranking') %></th>
          <th><%= t('.user') %></th>
          <th class="hide-for-small-only"><%= t('.completeness') %></th>
          <th class="hide-for-small-only"><%= t('.payment') %></th>
          <th><%= t('.points') %></th>
          <th>&nbsp;</th>
        </tr>
      </thead>
      <tbody>
        <% index, previous_points = 0, nil %>
        <% @bets.each do |bet| %>
          <% index += 1 if previous_points != bet.points %>
          <% previous_points = bet.points %>
          <tr>
            <td class="hide-for-small-only"><%= index %>º</td>
            <td><%= bet.user.name_or_email %></td>
            <td class="hide-for-small-only"><%= bet.percentage %></td>
            <td class="hide-for-small-only"><%= bet.payment_status %></td>
            <td><%= bet.points %></td>
            <td><%= link_to t('.view'), bet_path(bet) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="small-3 column">
    <h3><%= t('.prizes') %></h3>
    <% bet = @bets.first %>
    <ul>
      <li>
        <%= t('.paid_bets') %>: <%= @paid_bets_count %>
        <% if @paying_bets_count > 0 %>
          <ul>
            <li><%= t('.paying_bets') %>: <%= @paying_bets_count %></li>
          </ul>
        <% end %>
      </li>
      <% if @paid_bets_count > 0 %>
        <li>1º <%= t('.place') %>: <%= number_to_currency ((bet.prize_split[:first] / 100.0) * @paid_bets_count * bet.to_prize) %></li>
        <li>2º <%= t('.place') %>: <%= number_to_currency ((bet.prize_split[:second] / 100.0) * @paid_bets_count * bet.to_prize) %></li>
        <li>3º <%= t('.place') %>: <%= number_to_currency ((bet.prize_split[:third] / 100.0) * @paid_bets_count * bet.to_prize) %></li>
      <% end %>
    </ul>
    <p><%= t('.if_doubt_see_rules', the_rules_link: link_to(t('.the_rules'), help_path)).html_safe %></p>
  </div>
</div>

app/views/bets/matches.html.erb
<% content_for(:title) { t('.title') } %>

<div class="row">
  <div class="small-12 column">
    <h2><%= t '.my_bet' %></h2>
    <h3><%= Match.model_name.human(count: 2) %></h3>

    <dl class="sub-nav">
      <dt><%= t '.filter' %>:</dt>
      <dd class="<%= 'active' if (current_filter.blank? || current_filter.all?) %>"><%= link_to t('.all'), bet_matches_path %></dd>
      <dd class="<%= 'active' if current_filter.betted? %>"><%= link_to t('.betted'), bet_matches_path(filter: :betted) %></dd>
      <dd class="<%= 'active' if current_filter.to_bet? %>"><%= link_to t('.to_bet'), bet_matches_path(filter: :to_bet) %></dd>
    </dl>

    <% if @matches.empty? %>
      <p><%= t( current_filter.blank? ? '.none_to_show' : ".none_to_show_#{current_filter}") %>.</p>
    <% else %>
      <%= render partial: 'match', collection: @matches %>
    <% end %>
  </div>
</div>

app/views/bets/questions.html.erb
<% content_for(:title) { t('.title') } %>

<div class="row">
  <div class="small-12 column">
    <h2><%= t '.my_bet' %></h2>
    <h3><%= Question.model_name.human(count: 2) %></h3>

    <dl class="sub-nav">
      <dt><%= t '.filter' %>:</dt>
      <dd class="<%= 'active' if current_filter.blank? %>"><%= link_to t('.all'), bet_questions_path %></dd>
      <dd class="<%= 'active' if current_filter.betted? %>"><%= link_to t('.betted'), bet_questions_path(filter: :betted) %></dd>
      <dd class="<%= 'active' if current_filter.to_bet? %>"><%= link_to t('.to_bet'), bet_questions_path(filter: :to_bet) %></dd>
    </dl>

    <% if @questions.empty? %>
      <p><%= t( current_filter.blank? ? '.none_to_show' : ".none_to_show_#{current_filter}") %>.</p>
    <% else %>
      <%= render partial: 'question', collection: @questions %>
    <% end %>
  </div>
</div>

app/views/bets/show.html.erb
<% content_for(:title) { t('.title', user_name: @bet.user.name_or_email) } %>

<div class="row">
  <div class="small-12 column">
    <h2><%= Bet.model_name.human(count: 2) %></h2>
    <h3><%= @bet.user.name_or_email %></h3>

    <div class="bet-info">
      <ul class="disc">
        <li><%= t('.completeness') %>: <%= @bet.percentage %></li>
        <li><%= t('.payment') %>: <%= @bet.payment_status %></li>
        <li><%= t('.points') %>: <%= @bet.points %></li>
      </ul>
    </div>

    <p class="panel radius"><%= t('.showing_only_locked_events') %></p>

    <h4><%= Match.model_name.human(count: 2) %></h4>
    <p><%= @bet.matches_count %> / <%= @bet.bettable_or_locked_matches_count %> (<%= @bet.match_bets_percentage %>) <%= t('.matches_betted') %>, <%= @bet.match_bets_points %> <%= t('.points').downcase %></p>
    <table id="match_bets_table">
      <thead>
        <tr>
          <th class="text-center hide-for-small-only"><%= Match.model_name.human(count: 1) %></th>
          <th class="text-center" colspan="5"><%= t('.guess') %></th>
          <th class="text-center"><%= t('.points') %></th>
        </tr>
      </thead>
      <tbody>
        <% @bet.match_bets.each do |match_bet| %>
          <% match = match_bet.match %>
          <tr>
            <td>
              <a name="<%= match.css_id %>"></a>
              <%= link_to "##{match.number}", match_path(match) %>
            </td>
            <td class="text-center hide-for-small-only"><%= match.team_a_flag %></td>
            <td class="text-left"><%= match.team_a_name %></td>

            <td class="text-center">
              <%= match_bet.goals_a_if_locked %> x <%= match_bet.goals_b_if_locked %>
              <%= match_bet.penalty_winner_if_locked %>
            </td>

            <td class="text-right"><%= match.team_b_name %></td>
            <td class="text-center hide-for-small-only"><%= match.team_b_flag %></td>
            <td class="text-center"><%= match_bet.points_with_explanation %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <h4><%= Question.model_name.human(count: 2) %></h4>
    <p><%= @bet.questions_count %> / <%= @bet.bettable_or_locked_questions_count %> (<%= @bet.question_bets_percentage %>) <%= t('.questions_betted') %>, <%= @bet.question_bets_points %> <%= t('.points').downcase %></p>
    <table id="question_bets_table">
      <thead>
        <tr>
          <th class="text-center" colspan=2><%= Question.model_name.human(count: 1) %></th>
          <th class="text-center"><%= t('.answer') %></th>
          <th class="text-center"><%= t('.points') %></th>
        </tr>
      </thead>
      <tbody>
        <% @bet.question_bets.each do |question_bet| %>
          <% question = question_bet.question %>
          <tr>
            <td>
              <a name="<%= question.css_id %>"></a>
              <%= link_to "##{question.number}", question_path(question) %>
            </td>
            <td class="text-left"><%= truncate question.body, length: 50 %></td>
            <td class="text-left"><%= question_bet.answer_text_if_locked %></td>
            <td class="text-center"><%= question_bet.points_with_explanation %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div>
</div>