config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  get '/help' => 'pages#help', as: 'help'

  root 'dashboard#index'

  get '/login' => 'sessions#new', as: 'login'
  post '/one_time_token' => 'sessions#one_time_token', as: 'one_time_token'
  post '/login' => 'sessions#create'

  get '/logout' => 'sessions#destroy', as: 'logout'

  resources :matches, only: [:index, :show]
  resources :questions, only: [:index, :show]
  resources :bets, only: [:index, :show]

  get '/my_bet' => 'my_bet#show', as: 'my_bet'
  get '/my_bet/matches' => 'my_bet#matches', as: 'my_bet_matches'
  get '/my_bet/questions' => 'my_bet#questions', as: 'my_bet_questions'

  get '/my_bet/payment' => 'payments#new', as: 'my_bet_payment'
  post '/my_bet/payment' => 'payments#create'
  post '/payment_notifications' => 'payments#update', as: 'payment_notifications'

  get  '/my_bet/matches/:match_id' => 'match_bets#edit', as: 'my_match_bet'
  post '/my_bet/matches/:match_id' => 'match_bets#create'
  put  '/my_bet/matches/:match_id' => 'match_bets#update'

  get  '/my_bet/questions/:question_id' => 'question_bets#edit', as: 'my_question_bet'
  post '/my_bet/questions/:question_id' => 'question_bets#create'
  put  '/my_bet/questions/:question_id' => 'question_bets#update'

  namespace :admin do
    resources :matches, only: [:edit, :update]
    resources :questions, only: [:edit, :update]
  end

  # TODO limit access to admins, see https://github.com/mperham/sidekiq/wiki/Monitoring#security
  mount Sidekiq::Web => '/admin/sidekiq'

end

app/models/match.rb
class Match < ActiveRecord::Base
  include BettableEvent

  ROUNDS = %w( group round_16 quarter semi final )
  GROUPS = %w( A B C D E F G H )
  VENUES = {
    'am' => 'Arena Amazônia, Manaus, AM',
    'ba' => 'Arena Fonte Nova, Salvador, BA',
    'ce' => 'Estádio Castelão, Fortaleza, CE',
    'df' => 'Estádio Nacional (Mané Garrincha), Brasília, DF',
    'mg' => 'Estádio Mineirão, Belo Horizonte, MG',
    'mt' => 'Arena Pantanal, Cuiabá, MT',
    'pe' => 'Arena Pernambuco, Recife, PE',
    'pr' => 'Arena da Baixada, Curitiba, PR',
    'rj' => 'Estádio Jornalista Mário Filho (Maracanã), Rio de Janeiro, RJ',
    'rn' => 'Estádio das Dunas, Natal, RN',
    'rs' => 'Estádio Beira-Rio, Porto Alegre, RS',
    'sp' => 'Arena de São Paulo (Itaquerão), São Paulo, SP',
  }

  belongs_to :team_a, class_name: 'Team'
  belongs_to :team_b, class_name: 'Team'
  has_many :match_bets

  # belongs_to :winner, :class_name => 'Team' # TODO add winner_id to matches
  # belongs_to :loser, :class_name => 'Team' # TODO add loser_id to matches

  validates :round,
    presence: true,
    inclusion: { in: ROUNDS, allow_blank: true }

  validates :group,
    inclusion: { in: GROUPS, allow_blank: true }

  validates :played_on,
    presence: true,
    inclusion: { in: VENUES.keys, allow_blank: true }

  validates :goals_a,
    numericality: { only_integer: true, greater_than_or_equal_to: 0, allow_blank: true }

  validates :goals_b,
    numericality: { only_integer: true, greater_than_or_equal_to: 0, allow_blank: true }

  validates :penalty_goals_a,
    numericality: { only_integer: true, greater_than_or_equal_to: 0, allow_blank: true }

  validates :penalty_goals_b,
    numericality: { only_integer: true, greater_than_or_equal_to: 0, allow_blank: true }

  validate :teams_are_not_the_same
  validate :teams_must_be_of_the_same_group_as_the_match
  validate :no_draw_after_group_phase
  validate :no_penalty_goals_during_group_phase

  scope :with_known_teams, -> { where.not(team_a: nil, team_b: nil) }
  scope :with_known_goals, -> { where.not(goals_a: nil, goals_b: nil) }
  scope :bettable, -> { with_known_teams.not_locked }
  scope :scorable, -> { with_known_teams.with_known_goals.locked }

  # Returns the winner as a symbol `:team_a` or `:team_b` or `:draw` if it is a tie.
  def result
    return unless valid? && scorable?
    if goals_a == goals_b
      if drawable?
        :draw
      else
        penalty_goals_a > penalty_goals_b ? :team_a : :team_b
      end
    else
      goals_a > goals_b ? :team_a : :team_b
    end
  end

  def total_points
    (result_points + (2 * goal_points))
  end

  def result_points
    Integer(ENV.fetch('APP_MATCH_POINTS_RESULT', 6))
  end

  def goal_points
    Integer(ENV.fetch('APP_MATCH_POINTS_GOALS', 2))
  end

  # TODO spec
  def played?
    self.played_at < Time.zone.now &&
    self.with_known_goals? &&
      self.with_known_teams?
  end

  # TODO spec
  def drawable?
    self.round? && self.round == 'group'
  end

  # A match is bettable up to hours_before_start_time_to_bet hour before it starts,
  # and must have both teams known.
  def bettable?
    self.with_known_teams? && !self.locked?
  end

  def with_known_teams?
    self.team_a.present? && self.team_b.present?
  end

  # TODO spec
  def with_known_goals?
    self.goals_a.present? && self.goals_b.present?
  end

  def with_known_penalty_goals?
    self.penalty_goals_a.present? && self.penalty_goals_b.present?
  end

  def betted_by?(bet)
    MatchBet.exists?(match_id: self.id, bet_id: bet.id)
  end

  def played_on_text
    return nil unless self.played_on?
    VENUES[self.played_on]
  end

  # TODO spec
  def self.all_bettables_in_order
    self.ordered.with_known_teams.all
  end

  # Returns `true` if the match is ready to be scored.
  def scorable?
    return false unless locked?
    return false unless with_known_teams?
    return false unless with_known_goals?
    return false if goals_draw? && !drawable? && !with_known_penalty_goals?
    true
  end

  private

  # validation
  def teams_are_not_the_same
    if with_known_teams? &&
      self.team_a == self.team_b
      errors.add(:team_b_id, :equal_teams)
    end
  end

  # validation
  def teams_must_be_of_the_same_group_as_the_match
    if with_known_teams? &&
      self.group? &&
      [self.group, self.team_a.group, self.team_b.group].uniq.size != 1
      errors.add(:group, :not_the_same)
    end
  end

  # validation
  def no_draw_after_group_phase
    return unless with_known_teams? && with_known_goals? && !drawable?
    if goals_draw?
      if !with_known_penalty_goals?
        errors.add(:penalty_goals_a, :blank)
        errors.add(:penalty_goals_b, :blank)
      end
      if penalty_goals_draw?
        errors.add(:penalty_goals_b, :equal)
      end
    end
  end

  # validation
  def no_penalty_goals_during_group_phase
    if self.round == 'group'
      [:penalty_goals_a, :penalty_goals_b].each do |field|
        if !self.send(field).blank?
          errors.add(field, :present)
        end
      end
    end
  end

  def goals_draw?
    with_known_goals? && self.goals_a == self.goals_b
  end

  def penalty_goals_draw?
    with_known_penalty_goals? && self.penalty_goals_a == self.penalty_goals_b
  end

end

app/controllers/admin/matches_controller.rb
class Admin::MatchesController < AdminController

  before_action :find_match, except: [:index]

  # GET /admin/matches/:id/edit
  # Via: edit_admin_match_path(:id)
  #
  # Shows the form for the admin to change information of a match
  def edit
  end

  # PUT /admin/matches/:id
  # Via: admin_match_path(:id)
  #
  # Changes the information of a match by the admin
  def update
    updater = MatchUpdater.new(@_match, match_params)
    if updater.save
      flash[:success] = updater.message
      redirect_to match_path(@match)
    else
      flash.now[:error] = t('.update_error')
      render :edit
    end
  end

  private

  def find_match
    @_match = Match.includes([:team_a, :team_b]).find(params[:id])
    @match = MatchPresenter.new(@_match)
  end

  def match_params
    params.require(:match).permit(
      :team_a_id, :team_b_id, :goals_a, :goals_b, :penalty_goals_a, :penalty_goals_b
    )
  end

end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController

  # GET /matches
  # Via: matches_path
  def index
    @_matches = Match.includes([:team_a, :team_b]).all_in_order
    @matches = MatchPresenter.map(@_matches)
  end

  # GET /matches/:id
  # Via: match_path(:id)
  def show
    @_match = Match.find(params[:id])
    @match = MatchPresenter.new(@_match)
  end

end

app/views/matches/_match.html.erb
<div class="row">
  <div class="small-12 column">
    <p><%= match.round_text %></p>
    <p><%= l match.played_at, format: :detailed %></p>
    <p><%= match.played_on_text %></p>
    <p>
      <%= match.team_a_flag_or_? %>
      <%= match.team_a_name_or_? %>
      <%= match.goals_a_or_? %>
      <%= "(#{match.penalty_goals_a_or_?})".html_safe if match.with_known_penalty_goals? %>
       x
      <%= "(#{match.penalty_goals_b_or_?})".html_safe if match.with_known_penalty_goals? %>
      <%= match.goals_b_or_? %>
      <%= match.team_b_name_or_? %>
      <%= match.team_b_flag_or_? %>
      <% if match.with_known_penalty_goals? %>
        (<%= t('.on_penaltys') %>)
      <% end %>
    </p>
  </div>
</div>

app/views/matches/index.html.erb
<% content_for(:title) { Match.model_name.human(count: 2) } %>

<div class="row">
  <div class="small-12 column">
    <h2><%= Match.model_name.human(count: 2) %></h2>
  </div>
</div>

<div class="row">
  <div class="small-12 column">
    <table>
      <tbody>
        <% @matches.each do |match| %>
          <tr>
            <td><%= link_to "##{match.number}", match_path(match) %></td>
            <td class="hide-for-small-only"><%= match.round_text %></td>
            <td class="hide-for-small-only"><%= l match.played_at, format: :short %></td>
            <td class="text-center hide-for-small-only"><%= match.team_a_flag_or_? %></td>
            <td class="text-left"><%= match.team_a_name_or_? %></td>
            <td class="text-center">
              <%= match.goals_a_or_? %> x <%= match.goals_b_or_? %>
              <% if match.with_known_penalty_goals? %>
                <br /><%= match.penalty_goals_a_or_? %> x <%= match.penalty_goals_b_or_? %>
                <br />(<%= t('.on_penaltys') %>)
              <% end %>
            </td>
            <td class="text-right"><%= match.team_b_name_or_? %></td>
            <td class="text-center hide-for-small-only"><%= match.team_b_flag_or_? %></td>
            <td class="hide-for-small-only">
              <%= link_to t('.view'), match_path(match) %>
              <% if admin_logged_in? %>
                <%= link_to t('.edit'), edit_admin_match_path(match), class: 'admin-action' %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/matches/show.html.erb
<% content_for(:title) { "#{Match.model_name.human(count: 1)} ##{@match.number}" } %>

<div class="row">
  <div class="small-12 column">
    <h2><%= Match.model_name.human(count: 1) %> #<%= @match.number %></h2>
  </div>
</div>

<%= render partial: 'matches/match', object: @match %>

<div class="row">
  <div class="small-12 column">
    <% if admin_logged_in? %>
      <p><%= link_to t('.edit'), edit_admin_match_path(@match), class: 'admin-action' %></p>
    <% end %>
    <p><%= link_to t('.all'), matches_path %> | <%= @match.link_to_previous %> | <%= @match.link_to_next %></p>
  </div>
</div>

<div class="row">
  <div class="small-12 column">
    <h3><%= Bet.model_name.human(count: 2) %></h3>
  </div>
</div>

<div class="row">
  <div class="small-12 column">
    <table id="match_bets_table">
      <thead>
        <tr>
          <th class="text-left"><%= t('bets.show.better') %></th>
          <th class="text-center" colspan="3"><%= t('bets.show.guess') %></th>
          <th class="text-center"><%= t('bets.show.points') %></th>
        </tr>
      </thead>
      <tbody>
        <% @match.match_bets.each do |match_bet| %>
          <% bet = match_bet.bet %>
          <% user = bet.user %>
          <tr>
            <td>
              <a name="<%= bet.css_id %>"></a>
              <%= link_to user.name_or_email, bet_path(bet, anchor: @match.css_id) %>
            </td>
            <td class="text-left"><%= @match.team_a_name %></td>
            <td class="text-center">
              <%= match_bet.goals_a_if_locked %> x <%= match_bet.goals_b_if_locked %>
              <%= match_bet.penalty_winner_if_locked %>
            </td>
            <td class="text-right"><%= @match.team_b_name %></td>
            <td class="text-center"><%= match_bet.points_with_explanation %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>